### ISSUE TITLE
Invalid check for ESP header 1.71

### ISSUE THREAD

**Issue by alekulyn** [Michael-wigontherun/ESLifyEverything#26]
The compacted mod check in CompactedModData.cs is not valid for ESPFE header version 1.71, as the new minimum valid id is 0x0. This is the line with the bug in it: https://github.com/Michael-wigontherun/ESLifyEverything/blob/main/ESLifyEverything/FormData/CompactedModData.cs#L80

**Comment by alekulyn** [comment]
Additionally, any subplugins referencing ids under 0x800 also need to be on version 1.71, so the code renumbering the ids in the subplugins may also need to upgrade the version too.

**Comment by Michael-wigontherun** [comment]
No even on the 1.71 they still can be in the range of 800-fff. 1.71 opened it to be 000-fff.

I will open ESLify everything to the new 2000 forms. But I won't be doing anything until I get all the stuff worked out with Nexus.

**Comment by Blasg2** [comment]
Nexus is doing the virus thing? I hope it works out sometime!

**Comment by codegrizzly** [comment]
Hello. First, thank you for this utility. It has saved me countless hours. 
I'm commenting here, because I didn't want to open another issue if what I'm experiencing is the same thing, which I suspect it is. 

I am using 4.10.1 of EslifyEverything. I use a set of xEdit scripts. One to reset the header on all the plugins to 1.71. The other to list the esps that can be compacted. I'm assuming the issue is that EslifyEverything does not yet support the increased number of form ids or new records in the latest versions of Skyrim. When I attempted to use EslifyEverything after compacting and flagging an esp within the new id and record limit, I get the error below. 

```
Reading compacted mod data from .\CompactedForms\CACO Farm Overhaul.esp_ESlEverything.json

CACO Farm Overhaul.esp_ESlEverything.json is outdated or was not saved.

CACO Farm Overhaul.esp was not fully compacted. New forms detected. Recompact the plugin in xEdit, ensure you recompact the plugin in the output folder as well as set the esl flag.
Please delete previously edited and outputed data files and\or plugins for CACO Farm Overhaul.esp.
Then recompact and save CACO Farm Overhaul.esp in xEdit. Do not delete the CompactedModData file. It can still be updated.
ESLify Everything will ignore CACO Farm Overhaul.esp compacted mod data for this run.
```

**Comment by codegrizzly** [comment]
After taking a  look at the source this morning, while hacky and not a overall a good idea, if I add the line below to the CompactForms file for the few esps that I compacted that had more that the 2000 new records, ESlEverything would process them. For now, I won't compact any mods with more than 2000 new records, and will wait patiently for ESlEverything to be updated to support the new limit. 

`"NotCompactedData": true,`

Thanks again. Given how much time this utility saves me, I'd love to support the effort in some way. Do you have a Patreon or similar?

**Comment by codegrizzly** [comment]
Looks like I was mistaken. It isn't the number of files, it is the change in the header version. So, my issue is the same one as previously reported.

**Comment by Michael-wigontherun** [comment]
Try using the new prerelease version.

**Comment by codegrizzly** [comment]
Awesome. Will do. Thanks.

**Comment by codegrizzly** [comment]
Hi Michael,
Unfortunately, the 4.10.2 doesn't seem to like the 1.71 header.

```
Reading compacted mod data from .\CompactedForms\Vampire Clans and Bloodlines.esp_ESlEverything.json

Vampire Clans and Bloodlines.esp_ESlEverything.json is outdated or was not saved.

Vampire Clans and Bloodlines.esp was not fully compacted. New forms detected. Recompact the plugin in xEdit, ensure you recompact the plugin in the output folder as well as set the esl flag.
Please delete previously edited and outputed data files and\or plugins for Vampire Clans and Bloodlines.esp.
Then recompact and save Vampire Clans and Bloodlines.esp in xEdit. Do not delete the CompactedModData file. It can still be updated.
ESLify Everything will ignore Vampire Clans and Bloodlines.esp compacted mod data for this run.
```

Steps done:
1) Update header version
2) Save, restart xedit
3) Run script to identity plugins that can be eslified. (Script supports new larger new record amount)
4) Compact for esl
5) Add ESL flag
6) save and exit xedit
7) Run EslifyEverything (after deleting contents of script directory)

**Comment by codegrizzly** [comment]
As an experiment, I reinstalled the mod. Did not update the header version, so compacting starts the form ids at 800. Compacted it again, added the ESL flag. This time when I ran EslifyEverything, it worked fine. I can see you made the change in the code to allow for form ids starting a 0, Not sure why it didn't work.

Actually, I used the files in ReleaseSets thinking that was the new complied pre-release version. However, the src file in there still has the old limit. 
ReleaseSets/ESLifyEverything/ESLifyEverything/src/FormData/CompactedModData.cs
```
uint validMin = 0x000800;
uint validMax = 0x000fff;

foreach (IMajorRecordGetter? form in mod.EnumerateMajorRecords())
```

**Comment by codegrizzly** [comment]
I went ahead and cloned the repository locally and built the ESLifyEverything module from the main branch. That worked. Everything is running great now. The utility recognizes the lower form ids fine now. Thanks again for all the great work.

**Comment by joanreyes9999** [comment]
Hi @codegrizzly, could I ask how you managed this? No matter what I try, I continue getting this same error.

**Comment by Michael-wigontherun** [comment]
I already fixed the issue just download the prerelease

**Comment by joanreyes9999** [comment]
Hi Michael, I've downloaded the pre-release, but I'm still getting the same error. Looking through the files in the repository, I can see you made some changes to CompactedModData.cs and ESLifyEverything.csproj. They don't reflect in the pre-release, however, as lines still reflect as uint validMin = 0x000800 in the former and <PackageReference Include="Mutagen.Bethesda.Skyrim" Version="0.40.0" /> in the latter. I've tried to update them manually to match your changes, but still no luck. Just can't work it out. I'm on Skyrim v1.5.97; tried both with latest CK and backported one, but no luck. Don't get me wrong, this tool is magic, but I'd love to see it work to its full potential.

**Comment by cal1407** [comment]
Same here, tried running the prerelease version but still getting the error
